<!DOCTYPE html>
<html lang="ja">
<head charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TryCatch</title>
</head>
<body>
   <script>
        // throw 'エラーです';
        // const err = new Error(); // Errorクラスをインスタンス化
        // err.message = 'エラーです'; // messageプロパティ
        // throw err; // errを強制的に発生させる

       function getMonthName (month) {
            month = month -1 // 月の数字を配列のインデックスに合わせる
            const months = ['1月','2月','3月','4月','5月','6月','7月',
                    '8月','9月','10月','11月','12月'];

            if (months[month] != null) {
                return months[month];
            } else {
                throw new Error('入力値は無効です');

                // const err = new Error();
                // err.message = 'エラー';
                // throw err; // うまくエラーが表示されない。
            }
        }

        // monthName = getMonthName(13);

        try { 
            // テストする文
            monthName = getMonthName(15); // 関数は例外を投げることがある
        }
        catch (e) {
            console.log(e); // 例外オブジェクトをエラー処理部分に渡す
        }
   </script> 
</body>
</html>